complile:
	g++ -o spimSimFranke -I./include ./src/*.cpp

r:
	./spimSimFranke

run:
	./spimSimFranke

clean:
	rm ./spimSimFranke

c:
	rm ./spimSimFranke

lines:
	find . -name '*.cpp' -o -name '*.h' | xargs wc -l
l:
	find . -name '*.cpp' -o -name '*.h' | xargs wc -l
